namespace: istio-ingress
targetCustomizations:
- name: rancher-desktop
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: rancher-desktop
  kustomize:
    dir: overlays/rancher-desktop
