apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: clouddns-dns01-solver-svc-acct
  namespace: istio-ingress
spec:
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: clouddns-dns01-solver-svc-acct
      namespace: istio-ingress

